# Generated by Django 4.2.9 on 2024-01-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Product',
            new_name='product',
        ),
    ]
